### ISSUE TITLE
macOS 10.15 Catalina couldn't use lanms installed by pip

### ISSUE THREAD

**Issue by LiuZhe6** [Parquery/lanms#4]
Hello!

I have successfully installed `lanms`, but when I use it. The terminal gave me the message like this.
```
(base) ➜  lanms git:(master) ✗ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lanms
[1]    65635 segmentation fault  python
```

I have try to compile the source code. Actually, the `adaptor.so` was successfully generated. But when I called the function of `merge_quadrangle_n9`, the program was exit. The message I got is `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`.

What should I do next?

**Comment by mristin** [comment]
Hi @LiuZhe6,
We tested only on Linux. I don't use MacOS so I can't really help. It seems that it might be a general compilation issue on MacOS.

**Comment by LiuZhe6** [comment]
OK. Thank you. I will do my job on Linux.

**Comment by luksurious** [comment]
FYI I ran into a similar issue with a project using lanms, when using it on MacOS and miniconda.

I solved it by changing the Makefile as I described here https://github.com/argman/EAST/issues/174#issuecomment-710107426
