### ISSUE TITLE
lanms on window

### ISSUE THREAD

**Issue by Ash920** [Parquery/lanms#5]
Hello, 
I'm trying to install lanms on windows using:
 pip install lanms

I got the following error:

ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jcace\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jcace\\AppData\\Local\\Temp\\pip-install-zbq9phk1\\lanms\\setup.py'"'"'; __file__='"'"'C:\\Users\\jcace\\AppData\\Local\\Temp\\pip-install-zbq9phk1\\lanms\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jcace\AppData\Local\Temp\pip-pip-egg-info-n9cxwrgr'
         cwd: C:\Users\jcace\AppData\Local\Temp\pip-install-zbq9phk1\lanms\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jcace\AppData\Local\Temp\pip-install-zbq9phk1\lanms\setup.py", line 27, in <module>
        if subprocess.call(['make', '--always-make','-C', BASE_DIR]) != 0:
      File "C:\Users\jcace\Anaconda3\lib\subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\jcace\Anaconda3\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "C:\Users\jcace\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Any solutions?

**Comment by mristin** [comment]
Sorry, we develop on Linux, so no idea what is going on.

**Comment by Ash920** [comment]
thanks
